name: Terraform Remove + Apply

on:
  workflow_dispatch:  # allows manual trigger from GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init 

      # 5️⃣ Remove resource from state
      - name: Remove resource from Terraform state
        run: terraform refresh

      - name: Remove resource from Terraform state
        run: terraform terraform output eks_gateway_cluster_name

     
